import Head from 'next/head'
import { useState, useEffect } from 'react';
import Header from '../components/Header';
import tw from 'tailwind-styled-components';
import Goal from '../components/Goal';

export default function Home() {
  const [resumeData, setResumeData] = useState({});
  
  useEffect(() => {
    fetch("/resumeData.json")
      .then((res) => res.json())
      .then((data) => {
        setResumeData(data);
      });
  }, []);

  return (
    <Container>
      <Head>
        <title>Nariniaina Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <Header data={resumeData.main} />
      <Goal data={resumeData.main} />
    </Container>
  )
}

const Container = tw.div`
  bg-[#191B27]
`;